= Manage users and user groups
:toc: true

:page-title: Manage users
:page-pageid: api-user-management
:page-description: You can manage users and user groups using REST APIs

To provide access to ThoughtSpot content or define role-based privileges, you need to add users and groups in ThoughtSpot. You can create user accounts and user groups using xref:rest-api-reference.adoc[REST API endpoints].

== User creation and update

You can create users using the xref:user-api.adoc#create-user[/tspublic/v1/user/] REST API endpoint and update user profiles via a xref:user-api.adoc#update-user[PUT call].

When configuring xref:configure-saml.adoc[SAML SSO] in ThoughtSpot UI, you can select the *Automatically add SAML users to ThoughtSpot upon first authentication* option, which will use the values in the SAML assertion to create a user if they do not exist. ThoughtSpot can also add users to groups sent within the SAML assertion. To enable and configure the SAML groups capabilities, contact your ThoughtSpot team.

By default, ThoughtSpot sends e-mail messages to a new user and enables onboarding workflows when they first log in, even when you are embedding ThoughtSpot content. To alter this behavior at a system-wide level, you need to xref:customize-email-settings.adoc[Customize the onboarding settings]. The xref:user-api.adoc#update-user[update user REST API] also allows setting onboarding experience values for an individual user through the JSON object of the `content` argument. If you need to modify the  default behavior beyond the available UI options, contact your ThoughtSpot team.

== User group creation and update

Groups can be created via the xref:group-api.adoc#create-group[/tspublic/v1/group/] REST API endpoint.

xref:api-user-management.adoc#group-privileges[Group privileges] are set directly on groups, either at group creation time, an xref:group-api.adoc#update-group[update call], or through the xref:group-api.adoc#add-privilege[add privilege] and xref:group-api.adoc#remove-privilege[remove privilege] methods.

== Group privileges

Each user group includes a set of privileges for its users. When a user is assigned to a group in ThoughtSpot, the default privileges associated with a group are assigned to its users. The group privileges allow users belonging to a group to perform specific operations and access workflows. If a user belongs to more than one group, they will have the highest level of privileges from all the groups they belong to.

[NOTE]
====
If a user group belongs to another user group, it inherits privileges from its parent group.
====

include::{path}/group-privileges.adoc[]

[NOTE]
====
ThoughtSpot also has a default group called `ALL_GROUP`. When you create new users in ThoughtSpot, they are automatically added to `ALL_GROUP`. By default, the members of `ALL_GROUP` do not have permission to download or upload data. To globally add the following privileges to all the users in `ALL_GROUP`, you can use the Group APIs.
====
