= Integrate with embedding application UI
:toc: true

:page-title: Integrate with embedding application UI
:page-pageid: integrate-with-app-ui
:page-description: You can use Visual Embed SDK and REST API capabilities to integrate embedded ThoughtSpot with your application's UI

== Dynamic lists of ThoughtSpot content in menus and selection boxes
The more dynamic your content creation process is, the more likely you will want to automate the retrieval of lists of content a user can see. All ThoughtSpot content is referenced by GUIDs, which can be obtained directly from the URLs of the ThoughtSpot UI or via REST API metadata calls. Once the user session is established in the browser via SSO, any REST API can be called for the logged in user if you xref:api-auth-session.adoc[include the credentials in the request].

There are two REST API calls that provide the names and GUIDs to generate menu or selection box items: xref:metadata-api.adoc#metadata-list[metadata/list] and xref:metadata-api#object-header[metadata/listobjectheaders]. The metadata/list endpoint provides more information around tags than metadata/listobjectheaders, and is most likely the endpoint you will call. Both calls are scoped to the user and will only show the objects the user has access to.

You must specify what object type to receive - `PINBOARD_ANSWER_BOOK` for pinboards, `QUESTION_ANSWER_BOOK` for answers or `LOGICAL_TABLE` for data objects, which can take an additional `subtype` parameter to limit  specifically to ThoughtSpot tables, worksheets or views.

Both endpoints include parameters for sorting and a `category` parameter that can filter the response to the user's own created objects or objects they have favorited. 

Once the user has selected or click on an item, the GUID(s) must pass to the appropriate parameter in the options object of the Embed constructor: 

 - `pinboardId` for a xref:embed-pinboard.adoc[whole pinboard] in a PinboardEmbed object
 - `pinboardId` and `vizId` for an xref:embed-a-viz.adoc[individual visualization] from a pinboard through the PinboardEmbed object
 - `datasources` array for a xref:embed-search.adoc[blank SearchEmbed]
 - `answerId` for a SearchEmbed loading an xref:embed-search.adoc[existing Answer]

== Filters in embedding app UI
xref:runtime-filters.adoc[Runtime filters] can be tied into the embedding application, since they are set programmatically prior to loading the embedded ThoughtSpot content. If you want users to set filter values outside of the embedded ThoughtSpot content, display some type of filter UI in the embedding application, then set those values in the runtime filters section of the constructor of the *PinboardEmbed* object. 

ThoughtSpot pinboards have four levels of filters:

 - Row-level security (RLS) rules: Tied to the logged-in user and their group memberships
 - Runtime filters: Set via the Visual Embed SDK or URL parameters. Do not display as UI filter components
 - Search / answer filters: Established via the search definition, not visible as UI filter components on a pinboard, only in Explore or Edit modes. 
 - Pinboard filters: Visible as UI components at the top of a pinboard, affecting all answers on the pinboard

RLS rules are only affected by the SSO process, which makes them the appropriate layer for secure data filtering. The other filter types can all be adjusted by the end user in the browser. 

Embedded searches will always be filtered by RLS rules. The end user can create their own UI filters via search within the embedded search component.


== Handle load and errors with PinboardEmbed components
A common workflow is to use an overlay DIV element to hide the embed content until you know that SSO has completed and the content is fully loaded. If an error occurs in the process, you may prefer to display your own custom message to the end user rather than have them see the embedded ThoughtSpot content in an error state.

The Visual Embed SDK provides xref:events.adoc[events] to take action at various places within the loading process. The following events are related to the load process: 

 1. `Init` : Fires at the beginning of the loading process. 
 2. `NoCookieAccess` :  Some browsers (Safari in particular) default to strict settings on cookie origins that prohibit the standard SSO process. Fires if cookies are restricted by the browser
 3. `AuthExpire` : Fires if SSO does not complete and if the ThoughtSpot session times out at some point. Listen to the `AuthExpire` event in the load process to determine when it is safe to show the ThoughtSpot content, and listen to it after loading to hide the ThoughtSpot login screen if the session expires for some reason
 4. `AuthInit` : Fires when the SSO process has completed correctly. Does not fire when an SSO process fails, instead `AuthExpire` fires in that situation. The logged-in user GUID is available in the response of the `AuthInit` event.
 4. `Error` :  Fires if any other errors occur in the Visual Embed SDK process. Does not fire for errors within the embedded ThoughtSpot content
 5. `Load`: Fires as soon as the area for embedding is created, not when the content has begun or finished loading.
 6. `Data` : Fires only on SearchEmbed components. Never fires with a PinboardEmbed component

The full list events are defined in the link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts[types.ts, window=_blank] file of the Visual Embed SDK source.

`AuthExpire` and `AuthInit` can be used together to determine if the SSO process completed correctly. To determine if `AuthExpire` is firing because SSO did not complete or if the ThoughtSpot session timed out, you can set a variable to act as a flag for if SSO ever completed (*tsLoggedIn* in the example below). When `AuthInit` fires, set the flag to *true*. Have the callback function attached to `AuthExpire` look at the flag to determine which state change caused the `AuthExpire` event to fire.

[source,javascript]
----
 // Instantiate class for embedding a pinboard
 const embed = new PinboardEmbed("#thoughtspot-embed", {
     pinboardId: '<pinboard-guid>',
 });
 
let tsLoggedIn = false;
embed
    .on(EmbedEvent.Init, showLoader)
    .on(EmbedEvent.NoCookieAccess, showCookieSettingsMsg)
    .on(EmbedEvent.AuthInit, (response) => {
        // Set that AuthInit has fired
        tsLoggedIn = true;
        // authInit returns object -> {type: 'authInit', data: {userGuid: <guid>} } }
        let userGUID = response.data.userGuid;
    } )
    .on(EmbedEvent.AuthExpire, (response) => {
        // Handle if session dies while content shows
        if (tsLoggedIn == true){
            tsSessionTimeoutCleanup();
        }
        else {
            // Display custom message if SSO issues
            showSSOFailedMsg();
        }
    } )
    .on(EmbedEvent.Error, showGenericErrorMsg)
    .render()
----

== Custom actions and interaction events
xref:custom-action-intro.adoc[Custom actions] fire an event when a user clicks on a menu item when set to be xref:custom-action-callback.adoc[callback actions]. The event provides the custom action identifier, the data from the visualization and additional information depending on the configuration. 

Custom actions provide a way for interaction within the ThoughtSpot components to trigger further workflows within the embedding application. 

There are other xref:events.adoc#_embed_events[events] that fire as the user interacts with the SearchEmbed and PinboardEmbed components:
 
 - `Drilldown`
 - `VizPointDoubleClick`

See below for additional events that fire only on the SearchEmbed component.

== Size and placement of PinboardEmbed component within page
The first argument of the constructors of each the Embed classes in the Visual Embed SDK (xref:search-embed.adoc[SearchEmbed], xref:embed-pinboard.adoc[PinboardEmbed], etc.) is a *div* element in the embedding page, where the embedded ThoughtSpot content will load.

The second argument of the constructors is a JavaScript object of options, several of which control how the embedded content fill the div. 

`frameParams` is an object with `width` and `height` attributes. If `frameParams` is not included, the embedded ThoughtSpot will fill the entirety of the div, and resize automatically if the div adjusts in size. This is equivalent to `width '100%', height: '100%'`. When `width` and `height` are set to percentages, the embedded area will be that proportion of the embedded div. When set to exact pixel sizes, the embedded area size stays fixed regardless of what happens to the div.

When `fullHeight` is set to *true*, there will not be a scrollbar within the embedded pinboard area. 


[source,javascript]
----
{
  frameParams : { 'width' : '100%', 'height' : '100%' },
  fullHeight : false
}
----

== Control SearchEmbed component behavior
There are three general ways to use the xref:embed-search.adoc[SearchEmbed component] component:

 1. Load with no datasources selected
 2. Load with particular datasources
 3. Load an existing saved answer

In cases 1 and 2, you can also define items to appear in the search bar using the `searchOptions` object in the options object. `searchOptions` has two properties: `searchTokenString` and `executeSearch`. When `executeSearch` is *true*, the search component will load the chart or table automatically. If `executeSearch` is *false*, the search bar will display the terms from `searchTokenString` but the user must press the 'GO' button to make the search execute. 

The `forceTable` option causes the search to load in table mode rather than with the automatically chosen visualization. 

`collapseDataSources` and `hideDataSources` control the data source pane on the left side of the search component. When `hideDataSources` is *true*, there is no way for the user to see the data source pane, while `collapseDataSources` loads to only an icon which can be used to expand the pane.

=== Events
There are several events that fire only on the SearchEmbed component

 - `DataSourceSelected` : Fires when a change occurs in the data sources, including initial load of the SearchEmbed component. Can be used to hide a loader screen. Return object contains an array of the selected column GUIDs (accessible using `LOGICAL_COLUMN` type within metadata REST API commands).
 - `QueryChanged` : Fires when a change occurs in the search bar, including initial load of the SearchEmbed component. Returned object includes a `data.search` property with the TML search query from the search box
 - `Data` : 
 - `Load` : Fires on SearchEmbed when the 'GO' button is pressed
 
=== Alternative worklows
`hideResults` blocks the 'GO' button from displaying the chart or table results. It also blocks the `Data` event from firing


== Additional Resources

link:https://github.com/thoughtspot/ts_everywhere_resources/blob/master/apis/rest-api.js[Example implementation of REST API calls in JavaScript, window=_blank]
