= Integrate with embedding application UI
:toc: true

:page-title: Integrate with embedding application UI
:page-pageid: integrate-with-app-ui
:page-description: You can use Visual Embed SDK and REST API capabilities to integrate embedded ThoughtSpot with your application's UI

== Dynamic lists of ThoughtSpot content in menus and selection boxes
The more dynamic your content creation process is, the more likely you will want to automate the retrieval of lists of content a user can see. All ThoughtSpot content is referenced by GUIDs, which can be obtained directly from the URLs of the ThoughtSpot UI or via REST API metadata calls. Once the user session is established in the browser via SSO, any REST API can be called for the logged in user if you xref:api-auth-session.adoc[include the credentials in the request].

There are two REST API calls that provide the names and GUIDs to generate menu or selection box items: xref:metadata-api.adoc#metadata-list[metadata/list] and xref:metadata-api#object-header[metadata/listobjectheaders]. The metadata/list endpoint provides more information around tags than metadata/listobjectheaders, and is most likely the endpoint you will call. Both calls are scoped to the user and will only show the objects the user has access to.

You must specify what object type to receive - `PINBOARD_ANSWER_BOOK` for pinboards, `QUESTION_ANSWER_BOOK` for answers or `LOGICAL_TABLE` for data objects, which can take an additional `subtype` parameter to limit  specifically to ThoughtSpot tables, worksheets or views.

Both endpoints include parameters for sorting and a `category` parameter that can filter the response to the user's own created objects or objects they have favorited. 

== Filters in embedding app UI
xref:runtime-filters.adoc[Runtime filters] can be tied into the embedding application, since they are set programmatically prior to loading the embedded ThoughtSpot content. If you want users to set filter values outside of the embedded ThoughtSpot content, display some type of filter UI in the embedding application, then set those values in the runtime filters section of the constructor of the *PinboardEmbed* object. 

ThoughtSpot pinboards have four levels of filters:

 - Row-level security (RLS) rules: Tied to the logged-in user and their group memberships
 - Runtime filters: Set via the Visual Embed SDK or URL parameters. Do not display as UI filter components
 - Search / answer filters: Established via the search definition, not visible as UI filter components on a pinboard, only in Explore or Edit modes. 
 - Pinboard filters: Visible as UI components at the top of a pinboard, affecting all answers on the pinboard

RLS rules are only affected by the SSO process, which makes them the appropriate layer for secure data filtering. The other filter types can all be adjusted by the end user in the browser. 

Embedded searches will always be filtered by RLS rules. The end user can create their own UI filters via search within the embedded search component.


== Handle load and errors
A common workflow is to use an overlay DIV element to hide the embed content until you know that SSO has completed and the content is fully loaded. If an error occurs in the process, you may prefer to display your own custom message to the end user rather than have them see the embedded ThoughtSpot content in an error state.

The Visual Embed SDK provides xref:events.adoc[events] to take action at various places within the loading process. The following events are related to the load process: 

 1. `Init` : Fires at the beginning of the loading process. 
 2. `NoCookieAccess` :  Some browsers (Safari in particular) default to strict settings on cookie origins that prohibit the standard SSO process. Fires if cookies are restricted by the browser
 3. `AuthExpire` : Fires if SSO does not complete and if the ThoughtSpot session times out at some point. Listen to the `AuthExpire` event in the load process to determine when it is safe to show the ThoughtSpot content, and listen to it after loading to hide the ThoughtSpot login screen if the session expires for some reason
 4. `AuthInit` : Fires when the SSO process has completed correctly. Does not fire when an SSO process fails, instead `AuthExpire` fires in that situation. The logged-in username is available in the response of the `AuthInit` event.
 4. `Error` :  Fires if any other errors occur in the Visual Embed SDK process. Does not fire for errors within the embedded ThoughtSpot content
 5. `Load`: Fires as soon as the area for embedding is created, not when the content has begun or finished loading.
 6. `Data` : Fires only on SearchEmbed components. Never fires with a PinboardEmbed component

The full list events are defined in the link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts[types.ts, window=_blank] file of the Visual Embed SDK source.

`AuthExpire` and `AuthInit` can be used together to determine if the SSO process completed correctly. To determine if `AuthExpire` is firing because SSO did not complete or if the ThoughtSpot session timed out, you can set a variable to act as a flag for if SSO ever completed (*tsLoggedIn* in the example below). When `AuthInit` fires, set the flag to *true*. Have the callback function attached to `AuthExpire` look at the flag to determine which state change caused the `AuthExpire` event to fire.

[source,javascript]
----
 // Instantiate class for embedding a pinboard
 const embed = new PinboardEmbed("#thoughtspot-embed", {
     pinboardId: '<pinboard-guid>',
 });
 
 embed
    // Register event listeners
    .on(EmbedEvent.Init, showLoader)
    .on(EmbedEvent.Load, hideLoader)
    .on(EmbedEvent.NoCookieAccess, displayBrowserSettingsWarning)
    .on(EmbedEvent.AuthInit, (isLoggedIn) => {
        if (!successFlag) {
           displayAnalyticsErrorMsg();
        }
    })
    .on(EmbedEvent.Error, () => {
        showNoDataImage();
        hideLoader();
    })
    // Render pinboard
    .render();
----

== Sizing and placement within page
The first argument of the constructors of each the Embed classes in the Visual Embed SDK (xref:search-embed.adoc[SearchEmbed], xref:embed-pinboard.adoc[PinboardEmbed], etc.) is a *div* element in the embedding page, where the embedded ThoughtSpot content will load.

The second argument of the constructors is a JavaScript object of options, several of which control how the embedded content fill the div. 

`frameParams` is an object with `width` and `height` attributes. `fullHeight` controls whether the embedded pinboard area expands automatically based on the height of the . `defaultHeight` sets a minimum 

[source,javascript]
----
{
  frameParams : { 'width' : '100%', 'height' : '100%' },
  fullHeight : false,
  defaultHeight : '250px'
}
----







== Additional Resources

link:https://github.com/thoughtspot/ts_everywhere_resources/blob/master/apis/rest-api.js[Example implementation of REST API calls in JavaScript, window=_blank]
