= Integrate with embedding application UI
:toc: true

:page-title: Integrate with embedding application UI
:page-pageid: integrate-with-app-ui
:page-description: You can use Visual Embed SDK and REST API capabilities to integrate embedded ThoughtSpot with your application's UI


== Handle load and errors
The Visual Embed SDK provides xref:events.adoc[events] to take action at various places within the loading process. 

A common workflow is to use an overlay to hide the embed content until you know that SSO has completed and the content is fully loaded: 

 1. Display a custom loader overlay which visibly covers the same area on the page as the ThoughtSpot embed target div.
 2. Listen to the `NoCookieAccess` event to detect browsers with strict settings that prohibit the standard SSO process. Display message telling user to adjust their browser settings and reload the page.
 3. Listen to the `AuthInit` event to detect if the SSO process has completed correctly. If SSO fails, display a message saying "analytics is unavailable at this time"
 4. Listen to the `Error` event for any other errors that may occur
 5. If SSO succeeds, listen to the `Load` event and remove the loader overlay to display the ThoughtSpot content

[source,javascript]
----
 // Instantiate class for embedding a pinboard
 const embed = new PinboardEmbed("#thoughtspot-embed", {
     pinboardId: '<pinboard-guid>',
 });
 
 embed
    // Register event listeners
    .on(EmbedEvent.Init, showLoader)
    .on(EmbedEvent.Load, hideLoader)
    .on(EmbedEvent.NoCookieAccess, displayBrowserSettingsWarning)
    .on(EmbedEvent.AuthInit, (isLoggedIn) => {
        if (!successFlag) {
           displayAnalyticsErrorMsg();
        }
    })
    .on(EmbedEvent.Error, () => {
        showNoDataImage();
        hideLoader();
    })
    // Render pinboard
    .render();
----

== Sizing and placement within page
The first argument of the constructors of each the Embed classes in the Visual Embed SDK (xref:search-embed.adoc[SearchEmbed], xref:embed-pinboard.adoc[PinboardEmbed], etc.) is a *div* element in the embedding page, where the embedded ThoughtSpot content will load.

The second argument of the constructors is a JavaScript object of options, several of which control how the embedded content fill the div. 

`frameParams` is an object with `width` and `height` attributes. `fullHeight` controls whether the embedded pinboard area expands automatically based on the height of the . `defaultHeight` sets a minimum 

[source,javascript]
----
{
  frameParams : { 'width' : '100%', 'height' : '100%' },
  fullHeight : false,
  defaultHeight : '250px'
}
----


== Filters 
ThoughtSpot has four levels of filters:

 - Row-level security (RLS) rules: Tied to the logged-in user and their group memberships
 - Runtime filters: xref:runtime-filters.adoc[Set via the Visual Embed SDK] or URL parameters
 - Search / answer filters: Established via the search definition, not visible in the UI on a pinboard 
 - Pinboard filters: Visible at the top of a pinboard, affecting all answers on the pinboard

RLS rules are only affected by the SSO process, which makes them the appropriate layer for secure data filtering. The other filter types can all be adjusted by the end user in the browser.

Runtime filters can be tied into the embedding application, because they can be set programmatically prior to loading the embedded ThoughtSpot content. If you want users to set filter values outside of the embedded ThoughtSpot content, display some type of filter UI in the embedding application, then set those values in the runtime filters section of the constructor of the *PinboardEmbed* object. 


== Dynamic menus and selection boxes
The more dynamic your content creation process is, the more likely you will want to automate the retrieval of lists of content a user can see. All ThoughtSpot content is referenced by GUIDs, which can be obtained directly from the URLs of the ThoughtSpot UI or via REST API metadata calls. Once the user session is established in the browser via SSO, any REST API can be called for the logged in user if you xref:api-auth-session.adoc[include the credentials in the request].

There are two REST API calls that provide the names and GUIDs to generate menu or selection box items: xref:metadata-api.adoc#metadata-list[metadata/list] and xref:metadata-api#object-header[metadata/listobjectheaders]. The metadata/list endpoint provides more information around tags than metadata/listobjectheaders, and is most likely the endpoint you will call. Both calls are scoped to the user and will only show the objects the user has access to.

You must specify what object type to receive - `PINBOARD_ANSWER_BOOK` for pinboards, `QUESTION_ANSWER_BOOK` for answers or `LOGICAL_TABLE` for data objects, which can take an additional `subtype` parameter to limit  specifically to ThoughtSpot tables, worksheets or views.

Both endpoints include parameters for sorting and a `category` parameter that can filter the response to the user's own created objects or objects they have favorited. 

== Additional Resources

link:https://github.com/thoughtspot/ts_everywhere_resources/blob/master/apis/rest-api.js[Example implementation of REST API calls in JavaScript, window=_blank]
