# This is a basic workflow to help you get started with Actions

name: Generate TypeDocs

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Use NodeJS v14.19.0
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.19.0'

            # Run npm install
            - name: Run npm install
              run: npm install --legacy-peer-deps

            # Runs TypeScript compiler
            - name: Run TypeScript compiler
              run: npm run tsc

            # Runs docgen and update PR
            - name: Run docgen and update PR
              run: |
                  # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
                  git --version
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
                  gh pr checkout ${{ github.event.pull_request.number }}
                  npm run test
                  npm run docgen
                  npm run publish-dev
              env:
                  GITHUB_TOKEN: ${{ github.token }}
